# -*- coding: utf-8 -*-
"""annotation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QUxOw1IM4JmNOcLuTmxrh7EFRsqenisK
"""

import pandas as pd

def annotate_with_markers(adata, marker_dict):
    clusters = adata.obs['leiden'].cat.categories
    ann = {}
    for c in clusters:
        sub = adata[adata.obs['leiden']==c]
        scores = {}
        for ct, genes in marker_dict.items():
            present = [g for g in genes if g in sub.var_names]
            scores[ct] = float(sub[:, present].X.mean()) if present else 0.0
        ann[c] = max(scores.items(), key=lambda x: x[1])[0]
    ann_df = pd.DataFrame(list(ann.items()), columns=['cluster','label'])
    return ann_df