# -*- coding: utf-8 -*-
"""qc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QUxOw1IM4JmNOcLuTmxrh7EFRsqenisK
"""

import scanpy as sc

def qc_report(adata, out_png_prefix):
    sc.pp.calculate_qc_metrics(adata, inplace=True)
    sc.pl.violin(adata, ['n_genes_by_counts','total_counts','pct_counts_mt'], jitter=0.4, multi_panel=True, save=f"_{out_png_prefix}.png")
